/* Optional full-corpus Rijal view. It never reads or writes the reader's notes. */
(function(root){'use strict';
const $=id=>document.getElementById(id);
const client=new root.RijalDatabaseClient();
let offset=0,query='',request=0,detailRequest=0,rankedRows=[],rankedHasMore=false,booksPromise=null;
function element(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node}
function action(text,fn){const button=element('button',text,'btn compact');button.type='button';button.addEventListener('click',()=>Promise.resolve(fn()).catch(error));return button}
function error(e){$('corpusStatus').textContent=e.message||String(e)}
function citation(c){return [c?.title,c?.part_label,c?.printed_label].filter(Boolean).join(' · ')}
function open(){const modal=$('corpusModal');modal.classList.remove('hidden');$('corpusQuery').value=$('q')?.value.trim()||$('corpusQuery').value;$('corpusQuery').focus();if($('corpusQuery').value.trim())search(true)}
function openForName(name){$('corpusModal').classList.remove('hidden');$('corpusQuery').value=name||'';$('corpusQuery').focus();search(true)}
function close(){request++;detailRequest++;$('corpusModal').classList.add('hidden')}
const assessment=/جبل الحفظ وإمام الدنيا في فقه الحديث|ليس بثقة|ليس بالقوي|متهم بالكذب|كذاب|ضعيف(?: جدا)?|متروك|مجهول|لين الحديث|سيئ الحفظ|ثقة(?: ثبت| حافظ| مأمون)?|صدوق(?: له أوهام| يخطئ| سيئ الحفظ)?|مقبول|لا بأس به|صحابي/u;
function priority(title){const t=String(title||'');if(t.includes('تقريب التهذيب'))return 0;if(t.includes('تهذيب التهذيب'))return 1;if(t.includes('تهذيب الكمال')&&!t.includes('إكمال')&&!t.includes('تذهيب'))return 2;return 3}
function grade(row){return priority(row.citation?.title)===0?(row.title||'').match(assessment)?.[0]||null:null}
function rowLabel(row){return (grade(row)?'عبارة حكم في تقريب التهذيب: '+grade(row)+' · ':'')+(row.title||row.name_label||'مدخل مصدر')+' · '+citation(row.citation)}
async function rankedSearch(name){if(!booksPromise)booksPromise=client.books().catch(e=>{booksPromise=null;throw e});const books=await booksPromise;const preferred=books.filter(b=>priority(b.title)<3);const requests=[client.search(name,{scope:'entries',mode:'words',limit:100,offset:0}),...preferred.map(b=>client.search(name,{scope:'entries',mode:'words',book:b.id,limit:30,offset:0}))];const results=await Promise.all(requests);const seen=new Set(),rows=[];for(const result of results)for(const row of result.results){if(!seen.has(row.id)){seen.add(row.id);rows.push(row)}}rows.sort((a,b)=>Number(!!grade(b))-Number(!!grade(a))||priority(a.citation?.title)-priority(b.citation?.title)||a.id.localeCompare(b.id));return{results:rows,has_more:results.some(x=>x.has_more)}}
async function search(reset){if(reset)offset=0;query=$('corpusQuery').value.trim();const token=++request;detailRequest++;$('corpusStatus').textContent='جار البحث في قاعدة الرجال المحلية…';$('corpusResults').replaceChildren();$('corpusDetail').textContent='اختر مدخلاً لعرض نص المصدر وحالة الهوية.';if(!query){$('corpusStatus').textContent='اكتب اسماً للبحث.';return}try{if(reset||!rankedRows.length){const result=await rankedSearch(query);if(token!==request)return;rankedRows=result.results;rankedHasMore=result.has_more}const rows=rankedRows.slice(offset,offset+25);for(const row of rows)$('corpusResults').append(action(rowLabel(row),()=>showEntry(row.id)));$('corpusStatus').textContent=rows.length?'عرض '+(offset+1)+'–'+(offset+rows.length)+' من المواضع المرشحة؛ عبارات الحكم من عنوان تقريب التهذيب فقط.':'لا توجد نتائج في المجموعة المعروضة.';$('corpusPrev').hidden=offset===0;$('corpusNext').hidden=offset+25>=rankedRows.length;if(rankedHasMore&&offset+25>=rankedRows.length)$('corpusStatus').textContent+=' توجد نتائج إضافية في قاعدة البيانات؛ ضيّق الاسم للبحث عنها.'}catch(e){if(token===request)error(e)}}
async function showEntry(id){const token=++detailRequest,host=$('corpusDetail');host.textContent='جار فتح موضع المصدر…';let entry;try{entry=await client.entry(id)}catch(e){if(token===detailRequest)error(e);return}if(token!==detailRequest)return;host.replaceChildren(element('h2',entry.entry.title||'مدخل مصدر'),element('p',citation(entry.citation),'rijal-source'),element('p','مدخل من نص المصدر؛ تطابق الاسم وحده لا يثبت اتحاد الأشخاص.','small'),element('div',entry.text,'rijal-passage'));const sourceGrade=grade({title:entry.entry.title,citation:entry.citation});if(sourceGrade)host.append(element('p','عبارة حكم في عنوان تقريب التهذيب: '+sourceGrade+' · تحقق من هوية الراوي وسياق النص.','rijal-fact'));host.append(action('الصفحة الأصلية كاملة',async()=>{const page=await client.page(entry.page_id);if(token!==detailRequest)return;host.append(element('div',page.text,'rijal-passage'))}));let identity;try{identity=await client.identity(id)}catch(e){if(token===detailRequest)host.append(element('p','لم تُربط لهذا الموضع ترجمة مستخرجة في فهرس الهوية الحالي.','small'));return}if(token!==detailRequest)return;const labels={reviewed_person:'شخص روجعت هويته',needs_review:'هوية تحتاج مراجعة',provisional_cluster:'ربط مؤقت غير محسوم',unlinked_entry:'مدخل غير مربوط'};host.append(element('h3','الهوية: '+(labels[identity.identity_kind]||identity.identity_kind)),element('p','عدد المداخل: '+identity.entry_count+' · '+identity.name_key,'small'));if(identity.entry_count>1)host.append(action('المداخل المرتبطة',()=>showMembers(identity.identity_id,token,host)));try{const dates=await client.identityDates(id);if(token!==detailRequest)return;if(dates.claims?.length){host.append(element('h3','تواريخ الوفاة المروية'));for(const claim of dates.claims){const box=element('section');box.append(element('p',claim.year+' هـ · '+claim.exact_quote,'rijal-passage'));if(claim.page_id)box.append(action('صفحة دليل التاريخ',()=>showPage(claim.page_id,token,box)));host.append(box)}}}catch(e){}try{for(const relation of ['teacher','student']){const graph=await client.identityGraph(id,{relation,limit:8});if(token!==detailRequest)return;if(!graph.results.length)continue;host.append(element('h3',relation==='teacher'?'شيوخ مذكورون (أسماء غير محسومة)':'تلاميذ مذكورون (أسماء غير محسومة)'));for(const item of graph.results){const box=element('section');box.append(element('p',item.name+' · '+item.source_entries+' مدخل مصدر','small'));if(item.mention_id)box.append(action('مواضع الدليل',()=>showEvidence(id,relation,item.mention_id,token,box)),action('هويات أخرى تذكر الاسم',()=>showMention(item.mention_id,relation,token,box)));host.append(box)}}}catch(e){}
}
async function showPage(pageId,token,host){const page=await client.page(pageId);if(token!==detailRequest)return;host.append(element('p',citation(page.citation),'rijal-source'),element('div',page.text,'rijal-passage'))}
async function pageResults(host,token,fetch,render,limit=30){let offset=0;const box=element('section');host.append(box);async function more(){const result=await fetch(offset,limit);if(token!==detailRequest)return;for(const row of result.results)box.append(render(row));offset+=result.results.length;if(result.has_more){const button=action('عرض المزيد',async()=>{button.disabled=true;try{await more();button.hidden=true}catch(e){button.disabled=false;throw e}});box.append(button)}}await more()}
async function showMembers(identityId,token,host){await pageResults(host,token,(offset,limit)=>client.identityMembers(identityId,{offset,limit}),m=>action(m.name_label+' · '+m.book_id,()=>showEntry(m.entry_id)))}
async function showEvidence(entryId,relation,mentionId,token,host){const box=element('section');box.append(element('p','هذه مواضع ذكر الاسم، ولا تثبت اتحاد الهوية أو السماع.','small'));host.append(box);await pageResults(box,token,(offset,limit)=>client.graphEvidence(entryId,relation,mentionId,{offset,limit}),row=>{const item=element('div');item.append(element('p',row.entry_id+' · '+row.review_priority,'small'));if(row.page_id)item.append(action('صفحة المصدر',()=>showPage(row.page_id,token,item)));return item})}
async function showMention(mentionId,relation,token,host){const box=element('section');box.append(element('p','تشابه الاسم المذكور بين الهويات لا يثبت أن المقصود شخص واحد.','small'));host.append(box);await pageResults(box,token,(offset,limit)=>client.graphMention(mentionId,{relation,offset,limit}),row=>{const item=element('div');item.append(element('p',(row.display_name||row.identity_id)+' · '+row.source_entries+' مدخل مصدر · '+(row.identity_kind||''),'small'));item.append(action('مداخل هذه الهوية',()=>showMembers(row.identity_id,token,item)));return item})}
function showSanad(input,selected){const names=root.ShamelaSanad.parse(input);$('corpusModal').classList.remove('hidden');$('corpusResults').replaceChildren();$('corpusDetail').replaceChildren(element('h2','فحص أسماء السند في '+(selected?'النص المحدد':'الصفحة الحالية')),element('p','يُبحث كل اسم في جميع المصادر. عبارات الحكم المنقولة من عنوان تقريب التهذيب تُعرض أولاً؛ تطابق الاسم لا يثبت هوية الراوي أو درجة الحديث.','small'));$('corpusPrev').hidden=true;$('corpusNext').hidden=true;const token=++request;detailRequest++;$('corpusStatus').textContent=names.length?names.length+' أسماء مستخرجة بالترتيب · الأول: '+names[0]:'لم أتعرف على سند؛ حدد نص السند كاملا ثم أعد الفحص.';names.forEach((name,index)=>{const box=element('section');box.append(element('h3',(index+1)+' · '+name));$('corpusResults').append(box);rankedSearch(name).then(result=>{if(token!==request)return;box.append(element('p',result.results.length+' مداخل مرشحة'+(result.has_more?'؛ قد توجد مداخل إضافية':'')+' · الترتيب لا يثبت هوية الراوي','small'));for(const row of result.results.slice(0,10))box.append(action(rowLabel(row),()=>showEntry(row.id)));box.append(action('ابحث عن الاسم في جميع النتائج',()=>openForName(name)))},e=>{if(token===request)box.append(element('p',e.message||String(e),'small'))})})}
root.showFullCorpusSanad=showSanad;root.showFullCorpus=open;root.showFullCorpusForName=openForName;root.closeFullCorpus=close;
document.addEventListener('DOMContentLoaded',()=>{$('corpusSearch').addEventListener('click',()=>search(true));$('corpusQuery').addEventListener('keydown',e=>{if(e.key==='Enter')search(true)});$('corpusPrev').addEventListener('click',()=>{offset=Math.max(0,offset-25);search(false)});$('corpusNext').addEventListener('click',()=>{offset+=25;search(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('corpusModal').classList.contains('hidden'))close()})});
})(window);
