'use strict';
const $=id=>document.getElementById(id),fmt=n=>Number(n).toLocaleString('ar'),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
const kinds={birth:'المولد',death:'الوفاة',teachers:'الشيوخ',students:'التلاميذ',assessment:'عبارة تقييم',alias:'اسم أو كنية',family:'القرابة',cross_reference:'إحالة'};
const classes={biography_candidate:'ترجمة مرشحة',cross_reference_candidate:'إحالة قصيرة مرشحة',short_index_candidate:'مدخل فهرسي قصير',catalogue_or_index_candidate:'فهرسة أو بيانات كتاب'};
const subjects={unresolved_in_biography_context:'المقصود بالعبارة لم يُحسم',editorial_context_unresolved:'من الحاشية · يحتاج إلى مراجعة',possible_report_or_chain_assessment:'قد يكون الحكم على حديث أو إسناد',unassigned_source_context:'عبارة خارج ترجمة محددة'};
let offset=0,state={},requestVersion=0,detailVersion=0;
async function api(path,params={}){const u=new URL('/api/'+path,location.origin);for(const[k,v]of Object.entries(params))if(v!==''&&v!==undefined)u.searchParams.set(k,v);const r=await fetch(u);const j=await r.json();if(!r.ok)throw Error(j.error||'تعذر الطلب');return j}
function citation(c){return [c.title,c.part_label,c.printed_label||'بلا رقم مطبوع'].filter(Boolean).join(' · ')}
function button(text,fn){const b=el('button',text);b.type='button';b.onclick=()=>Promise.resolve(fn()).catch(error);return b}
function error(e){$('status').textContent=e.message}
function statementCard(r){const n=el('article',undefined,'card');n.append(el('h3',r.name_label||'عبارة غير مرتبطة بترجمة'),el('small',citation(r.citation)));const types=[...new Set(r.triggers.map(t=>t.kind))];for(const t of types)n.append(el('span',kinds[t]||t,'tag'));n.append(el('p',subjects[r.subject_status]||r.subject_status,'muted'),el('div',r.quote,'quote'));if(r.attribution_text)n.append(el('p','لفظ النسبة المستخرج: '+r.attribution_text+' — لم تُحسم هوية القائل.','muted'));n.append(button('صفحة المصدر',()=>openPage(r.page_id,r.start_offset,r.end_offset)));if(r.biography_id)n.append(document.createTextNode(' '),button('سياق الترجمة',()=>openBio(r.biography_id)));return n}
async function search(){const v=++requestVersion;$('status').textContent='جار البحث…';const r=await api(state.scope,{q:state.q,kind:state.kind,origin:state.origin,offset,limit:25});if(v!==requestVersion)return;$('results').replaceChildren();for(const row of r.results){if(state.scope==='statements')$('results').append(statementCard(row));else{const n=el('article',undefined,'card');n.append(el('h3',row.name_label),el('small',citation(row.citation)),el('p',classes[row.classification]),el('p',fmt(row.segment_count)+' مقطع صفحة · '+fmt(row.statement_count)+' عبارة'),button('فتح الترجمة',()=>openBio(row.id)));$('results').append(n)}}$('status').textContent=r.results.length?'عرض '+fmt(offset+1)+'–'+fmt(offset+r.results.length):'لا توجد نتائج لهذا البحث.';$('prev').hidden=offset===0;$('next').hidden=!r.has_more}
async function openBio(id,at=0,version){const v=version===undefined?++detailVersion:version;const r=await api('biography/'+encodeURIComponent(id),{offset:at,limit:12});if(v!==detailVersion)return;const host=$('detail');if(at===0){host.replaceChildren(el('h2',r.name_label),el('p',classes[r.classification],'tag'),el('p','حدود آلية: تتوقف عند العنوان التالي في الملف نفسه. لا تمثل هوية محققة.','notice'));host.append(button('عبارات هذه الترجمة',async()=>{const a=await api('statements',{bio:id,limit:100});if(v!==detailVersion)return;const box=el('section');for(const row of a.results)box.append(statementCard(row));if(a.has_more)box.append(el('p','توجد عبارات إضافية؛ استخدم البحث بالاسم أو بالكلمات لتضييق النتائج.'));host.prepend(box)}));showIdentity(id,v).catch(error)}for(const g of r.segments){const n=el('div',undefined,'segment');n.append(el('small',citation(g.citation)+(g.role==='continuation'?' · استمرار في صفحة تالية':'')),el('div',g.text,'source'),button('صفحة المصدر كاملة',()=>openPage(g.page_id,g.start_offset,g.end_offset)));host.append(n)}if(r.has_more){const b=button('تحميل المقاطع التالية',async()=>{b.remove();await openBio(id,at+r.limit,v)});host.append(b)}}
async function openPage(id,a,b){const v=++detailVersion;const p=await api('page/'+encodeURIComponent(id));if(v!==detailVersion)return;const host=$('detail');host.replaceChildren(el('h2',citation(p.citation)));const pre=el('div',undefined,'source'),chars=Array.from(p.text);pre.append(document.createTextNode(chars.slice(0,a).join('')),el('mark',chars.slice(a,b).join('')),document.createTextNode(chars.slice(b).join('')));host.append(pre);pre.querySelector('mark').scrollIntoView({block:'center',behavior:'smooth'})}
async function showIdentity(entryId,version){let row;try{row=await api('identity/entry/'+encodeURIComponent(entryId))}catch(e){return}if(version!==detailVersion)return;const labels={reviewed_person:'شخص روجعت هويته',needs_review:'هوية تحتاج مراجعة',provisional_cluster:'ربط مؤقت يحتاج مراجعة',unlinked_entry:'مدخل لم يُربط بغيره'};const box=el('section',undefined,'card');box.append(el('h3','الهوية: '+(labels[row.identity_kind]||row.identity_kind)),el('p','عدد المداخل المرتبطة: '+fmt(row.entry_count)+' · مجموعة الاسم: '+row.name_key,'muted'));if(row.entry_count>1)box.append(button('عرض المداخل المرتبطة',async()=>{const data=await api('identity/members/'+encodeURIComponent(row.identity_id),{limit:100});if(version!==detailVersion)return;const list=el('div');for(const member of data.results)list.append(el('p',member.name_label+' · '+member.book_id+' · '+member.entry_id));if(data.has_more)list.append(el('p','توجد مداخل إضافية؛ تُعرض أول 100 فقط.'));box.append(list)}));$('detail').prepend(box)}
$('search').onsubmit=e=>{e.preventDefault();offset=0;state={scope:$('scope').value,q:$('q').value.trim(),kind:$('kind').value,origin:$('origin').value};search().catch(error)};
function filters(){const disabled=$('scope').value!=='statements';$('kind').disabled=disabled;$('origin').disabled=disabled}$('scope').onchange=filters;filters();$('prev').onclick=()=>{offset=Math.max(0,offset-25);search().catch(error)};$('next').onclick=()=>{offset+=25;search().catch(error)};
api('stats').then(r=>{const s=r.summary;$('stats').textContent=fmt(s.biographies)+' مدخل ترجمة مرشح · '+fmt(s.statements)+' موضع عبارة · '+fmt(s.distinct_statement_texts)+' نص عبارة متميز';$('search').requestSubmit()}).catch(error);
