'use strict';
const $=id=>document.getElementById(id), fmt=n=>Number(n).toLocaleString('ar');
let offset=0,queryState=null,searchVersion=0,pageVersion=0;
function el(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e}
function button(text,fn){const b=el('button',text,'secondary');b.type='button';b.onclick=fn;return b}
async function api(path,params){const u=new URL('/api/v1/'+path,location.origin);if(params)for(const [k,v]of Object.entries(params))if(v!==null&&v!==undefined&&v!=='')u.searchParams.set(k,v);const r=await fetch(u);const data=await r.json();if(!r.ok)throw Error(data.error||r.statusText);return data}
function citation(c){return c.title+' · '+(c.part_label||'')+' · '+(c.printed_label||'موضع '+fmt(c.ordinal+1)+' (بلا ترقيم في المصدر)')}
function error(e){$('status').textContent='تعذر إتمام الطلب: '+e.message}
async function search(){const version=++searchVersion;$('status').textContent='جار البحث…';try{const result=await api('search',{...queryState,offset,limit:25});if(version!==searchVersion)return;$('results').replaceChildren();for(const row of result.results){const b=el('button',undefined,'result');b.type='button';b.append(el('strong',row.title||row.citation.title));b.append(el('small',citation(row.citation)));if(row.excerpt)b.append(el('p',row.excerpt.text));if(row.source_count>1)b.append(el('small','النص نفسه في '+fmt(row.source_count)+' مواضع'));if(row.kind)b.append(el('small',row.kind==='source_heading'?'عنوان مصدر · يحتاج إلى مراجعة':'مدخل مرشح · غير محقق'));b.onclick=()=>openPage(row.page_id,row.start_offset,row.end_offset);$('results').append(b)}$('status').textContent=result.results.length?'عرض '+fmt(offset+1)+'–'+fmt(offset+result.results.length)+(result.has_more?' · توجد نتائج أخرى':'')+(queryState.scope==='pages'?' · الصفحات المتطابقة مجمعة':''):'لم تُعثر على نتائج. جرّب جميع النصوص أو جزءًا أقصر من الاسم.';$('back').hidden=offset===0;$('more').hidden=!result.has_more}catch(e){error(e)}}
function sliceText(text,start,end){return Array.from(text).slice(start,end).join('')}
function appendText(host,text,start,end){const chars=Array.from(text);if(Number.isInteger(start)&&Number.isInteger(end)&&start>=0&&end>start&&end<=chars.length){host.append(document.createTextNode(chars.slice(0,start).join('')),el('mark',chars.slice(start,end).join('')),document.createTextNode(chars.slice(end).join('')))}else host.textContent=text}
async function openPage(id,start,end){const version=++pageVersion;try{const p=await api('page/'+id);if(version!==pageVersion)return;const host=$('page');host.replaceChildren();host.append(el('h2',p.citation.title));const meta=[citation(p.citation),p.citation.author?'المؤلف: '+p.citation.author:'',p.citation.edition?'الطبعة: '+p.citation.edition:'',p.citation.publisher?'الناشر: '+p.citation.publisher:'','ملف المصدر: '+p.citation.zip_path].filter(Boolean).join('\n');host.append(el('div',meta,'page-meta'));const nav=el('div',undefined,'toolbar');if(p.previous)nav.append(button('الصفحة السابقة',()=>openPage(p.previous)));if(p.next)nav.append(button('الصفحة التالية',()=>openPage(p.next)));nav.append(button('نسخ المرجع',async()=>{try{await navigator.clipboard.writeText(meta+'\nمعرف الصفحة: '+p.id);$('status').textContent='نُسخ المرجع.'}catch(e){error(e)}}));host.append(nav);const text=el('div',undefined,'source-text');appendText(text,p.text,start,end);host.append(text);
const refs=el('details');refs.append(el('summary','مواضع هذا النص المتطابق ('+fmt(p.source_count)+')'));const refbox=el('div',undefined,'source-list');refs.append(refbox);let loaded=false;refs.ontoggle=async()=>{if(refs.open&&!loaded){loaded=true;try{await loadSources(refbox,'sources',{text_id:p.text_id})}catch(e){refbox.textContent=e.message}}};host.append(refs);
const duplicates=el('details');duplicates.append(el('summary','الفقرات المتكررة في هذه الصفحة'));const dupbox=el('div',undefined,'source-list');duplicates.append(dupbox);let dupLoaded=false;duplicates.ontoggle=async()=>{if(duplicates.open&&!dupLoaded){dupLoaded=true;try{const rows=await api('duplicates',{text_id:p.text_id});if(!rows.length)dupbox.textContent='لا توجد فقرات متطابقة مفهرسة متكررة في هذه الصفحة.';for(const row of rows){const d=el('details');d.append(el('summary',sliceText(p.text,row.start_offset,Math.min(row.end_offset,row.start_offset+100))+'… · '+fmt(row.source_occurrences)+' مواضع'));const box=el('div',undefined,'source-list');d.append(box);let did=false;d.ontoggle=async()=>{if(d.open&&!did){did=true;try{await loadSources(box,'passage-sources',{id:row.passage_id})}catch(e){box.textContent=e.message}}};dupbox.append(d)}}catch(e){dupbox.textContent=e.message}}};host.append(duplicates);
if(p.mentions.length){const rel=el('details');rel.append(el('summary','عبارات العلاقات المستخرجة ('+fmt(p.mentions.length)+')'));rel.append(el('p','هذه إشارات نصية غير محققة؛ لا تثبت وحدها هوية الشخص أو السماع المباشر.','notice'));for(const m of p.mentions){const box=el('div',undefined,'evidence');box.append(el('small',m.in_footnote?'من الحاشية':'من نص الصفحة'),el('div',m.evidence),button('تحديد العبارة',()=>openPage(p.id,m.start_offset,m.end_offset)));rel.append(box)}host.append(rel)}
if(p.raw_source_available){const a=el('a','تنزيل ملف HTML الأصلي');a.href='/api/v1/raw/'+p.source_id;a.download='';host.append(a)}else host.append(el('p','لفتح ملف HTML الأصلي أيضًا، ضع أرشيف المصادر الأصلي في مجلد sources. النصوص والمراجع والبحث متاحة دون هذه الخطوة.','muted'));
history.replaceState(null,'','#page='+p.id);if(innerWidth<760)host.scrollIntoView({behavior:'smooth'});if(start!==undefined)text.querySelector('mark')?.scrollIntoView({block:'center',behavior:'smooth'})}catch(e){error(e)}}
async function loadSources(box,route,params,offset=0){const result=await api(route,{...params,offset,limit:100});for(const c of result.results)box.append(button(citation(c),()=>openPage(c.page_id,c.start_offset,c.end_offset)));if(result.has_more){const next=button('عرض مواضع أخرى',async()=>{next.remove();try{await loadSources(box,route,params,offset+100)}catch(e){box.append(el('p',e.message))}});box.append(next)}}
$('searchForm').onsubmit=e=>{e.preventDefault();offset=0;queryState={q:$('query').value.trim(),scope:$('scope').value,mode:$('mode').value,book:$('book').value};if(queryState.q)search()};$('more').onclick=()=>{offset+=25;search()};$('back').onclick=()=>{offset=Math.max(0,offset-25);search()};
Promise.all([api('stats'),api('books')]).then(([s,books])=>{$('stats').textContent=fmt(s.books)+' مجموعة مصدر · '+fmt(s.source_files)+' ملفًا · '+fmt(s.pages)+' موضع صفحة · '+fmt(s.page_texts)+' نص صفحة متميز';for(const b of books){const o=el('option',b.source_group);o.value=b.id;$('book').append(o)}const params=new URLSearchParams(location.search);if(params.get('q')){$('query').value=params.get('q');$('searchForm').requestSubmit()}const id=new URLSearchParams(location.hash.slice(1)).get('page');if(id)openPage(id)}).catch(error);
