/* Optional full-corpus Rijal view. It never reads or writes the reader's notes. */
(function(root){'use strict';
const $=id=>document.getElementById(id);
const client=new root.RijalDatabaseClient();
let offset=0,query='',request=0,detailRequest=0;
function element(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node}
function action(text,fn){const button=element('button',text,'btn compact');button.type='button';button.addEventListener('click',()=>Promise.resolve(fn()).catch(error));return button}
function error(e){$('corpusStatus').textContent=e.message||String(e)}
function citation(c){return [c?.title,c?.part_label,c?.printed_label].filter(Boolean).join(' · ')}
function open(){const modal=$('corpusModal');modal.classList.remove('hidden');$('corpusQuery').value=$('rijalQuery')?.value.trim()||$('q')?.value.trim()||$('corpusQuery').value;$('corpusQuery').focus();if($('corpusQuery').value.trim())search(true)}
function openForName(name){$('corpusModal').classList.remove('hidden');$('corpusQuery').value=name||'';$('corpusQuery').focus();search(true)}
function close(){request++;detailRequest++;$('corpusModal').classList.add('hidden')}
async function search(reset){if(reset)offset=0;query=$('corpusQuery').value.trim();const token=++request;detailRequest++;$('corpusStatus').textContent='جار البحث في قاعدة الرجال المحلية…';$('corpusResults').replaceChildren();$('corpusDetail').textContent='اختر مدخلاً لعرض نص المصدر وحالة الهوية.';if(!query){$('corpusStatus').textContent='اكتب اسماً للبحث.';return}try{const result=await client.search(query,{scope:'entries',mode:'words',limit:25,offset});if(token!==request)return;for(const row of result.results){const label=row.title||row.name_label||'مدخل مصدر';$('corpusResults').append(action(label+' · '+citation(row.citation),()=>showEntry(row.id)))}$('corpusStatus').textContent=result.results.length?'عرض '+(offset+1)+'–'+(offset+result.results.length)+' من المواضع المرشحة.':'لا توجد نتائج.';$('corpusPrev').hidden=offset===0;$('corpusNext').hidden=!result.has_more}catch(e){if(token===request)error(e)}}
async function showEntry(id){const token=++detailRequest,host=$('corpusDetail');host.textContent='جار فتح موضع المصدر…';let entry;try{entry=await client.entry(id)}catch(e){if(token===detailRequest)error(e);return}if(token!==detailRequest)return;host.replaceChildren(element('h2',entry.entry.title||'مدخل مصدر'),element('p',citation(entry.citation),'rijal-source'),element('p','مدخل من نص المصدر؛ تطابق الاسم وحده لا يثبت اتحاد الأشخاص.','small'),element('div',entry.text,'rijal-passage'));host.append(action('الصفحة الأصلية كاملة',async()=>{const page=await client.page(entry.page_id);if(token!==detailRequest)return;host.append(element('div',page.text,'rijal-passage'))}));let identity;try{identity=await client.identity(id)}catch(e){if(token===detailRequest)host.append(element('p','لم تُربط لهذا الموضع ترجمة مستخرجة في فهرس الهوية الحالي.','small'));return}if(token!==detailRequest)return;const labels={reviewed_person:'شخص روجعت هويته',needs_review:'هوية تحتاج مراجعة',provisional_cluster:'ربط مؤقت غير محسوم',unlinked_entry:'مدخل غير مربوط'};host.append(element('h3','الهوية: '+(labels[identity.identity_kind]||identity.identity_kind)),element('p','عدد المداخل: '+identity.entry_count+' · '+identity.name_key,'small'));if(identity.entry_count>1)host.append(action('المداخل المرتبطة',async()=>{const members=await client.identityMembers(identity.identity_id,{limit:30});if(token!==detailRequest)return;const box=element('section');for(const m of members.results)box.append(action(m.name_label+' · '+m.book_id,()=>showEntry(m.entry_id)));if(members.has_more)box.append(element('p','توجد مداخل إضافية في قاعدة البيانات.','small'));host.append(box)}));try{const dates=await client.identityDates(id);if(token!==detailRequest)return;if(dates.claims?.length){host.append(element('h3','تواريخ الوفاة المروية'));for(const claim of dates.claims){const box=element('section');box.append(element('p',claim.year+' هـ · '+claim.exact_quote,'rijal-passage'));if(claim.page_id)box.append(action('صفحة دليل التاريخ',()=>showPage(claim.page_id,token,box)));host.append(box)}}}catch(e){}try{for(const relation of ['teacher','student']){const graph=await client.identityGraph(id,{relation,limit:8});if(token!==detailRequest)return;if(!graph.results.length)continue;host.append(element('h3',relation==='teacher'?'شيوخ مذكورون (أسماء غير محسومة)':'تلاميذ مذكورون (أسماء غير محسومة)'));for(const item of graph.results){const box=element('section');box.append(element('p',item.name+' · '+item.source_entries+' مدخل مصدر','small'));if(item.mention_id)box.append(action('مواضع الدليل',()=>showEvidence(id,relation,item.mention_id,token,box)));host.append(box)}}}catch(e){}
}
async function showPage(pageId,token,host){const page=await client.page(pageId);if(token!==detailRequest)return;host.append(element('p',citation(page.citation),'rijal-source'),element('div',page.text,'rijal-passage'))}
async function showEvidence(entryId,relation,mentionId,token,host){const evidence=await client.graphEvidence(entryId,relation,mentionId,{limit:30});if(token!==detailRequest)return;const box=element('section');box.append(element('p','هذه مواضع ذكر الاسم، ولا تثبت اتحاد الهوية أو السماع.','small'));for(const row of evidence.results){const item=element('div');item.append(element('p',row.name_label||row.entry_id||'موضع مصدر','small'));if(row.page_id)item.append(action('صفحة المصدر',()=>showPage(row.page_id,token,item)));box.append(item)}if(evidence.has_more)box.append(element('p','توجد مواضع إضافية.','small'));host.append(box)}
root.showFullCorpus=open;root.showFullCorpusForName=openForName;root.closeFullCorpus=close;
document.addEventListener('DOMContentLoaded',()=>{$('corpusSearch').addEventListener('click',()=>search(true));$('corpusQuery').addEventListener('keydown',e=>{if(e.key==='Enter')search(true)});$('corpusPrev').addEventListener('click',()=>{offset=Math.max(0,offset-25);search(false)});$('corpusNext').addEventListener('click',()=>{offset+=25;search(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('corpusModal').classList.contains('hidden'))close()})});
})(window);
