/* Optional full-corpus Rijal view. It never reads or writes the reader's notes. */
(function(root){'use strict';
const $=id=>document.getElementById(id);
const client=new root.RijalDatabaseClient();
let offset=0,query='',request=0,detailRequest=0,rankedRows=[],rankedHasMore=false,rankedCompanionNote='',booksPromise=null;
function element(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node}
function action(text,fn){const button=element('button',text,'btn compact');button.type='button';button.addEventListener('click',()=>Promise.resolve(fn()).catch(error));return button}
function error(e){$('corpusStatus').textContent=e.message||String(e)}
function citation(c){return [c?.title,c?.part_label,c?.printed_label].filter(Boolean).join(' · ')}
function open(){const modal=$('corpusModal');modal.classList.remove('hidden');$('corpusQuery').value=$('q')?.value.trim()||$('corpusQuery').value;$('corpusQuery').focus();if($('corpusQuery').value.trim())search(true)}
function openForName(name){$('corpusModal').classList.remove('hidden');$('corpusQuery').value=name||'';$('corpusQuery').focus();search(true)}
function close(){request++;detailRequest++;$('corpusModal').classList.add('hidden')}
const assessment=/جبل الحفظ وإمام الدنيا في فقه الحديث|ليس بثقة|ليس بالقوي|متهم بالكذب|كذاب|ضعيف(?: جدا)?|متروك|مجهول|لين الحديث|سيئ الحفظ|ثقة(?: ثبت| حافظ| مأمون)?|صدوق(?: له أوهام| يخطئ| سيئ الحفظ)?|مقبول|لا بأس به|صحابي(?:ة)?/u;
function companionBook(title){return /سلم الوصول إلى طبقات الفحول|الإصابة في تمييز الصحابة|الاستيعاب في معرفة الأصحاب|أسد الغابة في معرفة الصحابة|معرفة الصحابة/u.test(String(title||''))}
function priority(title,companion=false){const t=String(title||'');if(t.includes('تقريب التهذيب'))return 0;if(companion&&companionBook(t))return 1;if(t.includes('تهذيب التهذيب'))return companion?2:1;if(t.includes('تهذيب الكمال')&&!t.includes('إكمال')&&!t.includes('تذهيب'))return companion?3:2;return companionBook(t)?4:5}
function normalizedName(s){return String(s||'').normalize('NFD').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/(^|\s)ابن(?=\s|$)/gu,'$1بن').replace(/[\u200b-\u200f\u0640]/g,'').replace(/\s+/g,' ').trim()}
function headingMatch(row,name){const head=normalizedName(row.title).replace(/^[\s\d٠-٩.()\-–«»"“”]+/u,'');return head.startsWith(normalizedName(name))}
function grade(row){return priority(row.citation?.title)===0?(row.title||'').match(assessment)?.[0]||null:null}
function rowLabel(row){return (grade(row)?'عبارة حكم في تقريب التهذيب: '+grade(row)+' · ':'')+(row.title||row.name_label||'مدخل مصدر')+' · '+citation(row.citation)}
async function rankedSearch(name){const global=await client.search(name,{scope:'entries',mode:'words',limit:100,offset:0});let books=[];try{if(!booksPromise)booksPromise=client.books().catch(e=>{booksPromise=null;throw e});books=await booksPromise}catch(e){}const preferred=books.filter(b=>priority(b.title)<5);const extras=await Promise.allSettled(preferred.map(b=>client.search(name,{scope:'entries',mode:'words',book:b.id,limit:30,offset:0})));const results=[global,...extras.filter(x=>x.status==='fulfilled').map(x=>x.value)];const seen=new Set(),rows=[];for(const result of results)for(const row of result.results||[]){if(!seen.has(row.id)){seen.add(row.id);rows.push(row)}}const companion=rows.some(r=>headingMatch(r,name)&&(grade(r)==='صحابي'||grade(r)==='صحابية'));rows.sort((a,b)=>Number(headingMatch(b,name))-Number(headingMatch(a,name))||Number(!!grade(b))-Number(!!grade(a))||priority(a.citation?.title,companion)-priority(b.citation?.title,companion)||a.id.localeCompare(b.id));const companionNote=companion&&!books.some(b=>b.title.includes('سلم الوصول إلى طبقات الفحول'))?'سلم الوصول غير موجود في الكتب المتاحة لهذه الخدمة؛ تُعرض المصادر الأخرى مع إبقاء الهوية للمراجعة.':'';return{results:rows,has_more:results.some(x=>x.has_more),companionNote,partial:extras.some(x=>x.status==='rejected')}}
async function search(reset){if(reset)offset=0;query=$('corpusQuery').value.trim();const token=++request;detailRequest++;$('corpusStatus').textContent='جار البحث في قاعدة الرجال المحلية…';$('corpusResults').replaceChildren();$('corpusDetail').textContent='اختر مدخلاً لعرض نص المصدر وحالة الهوية.';if(!query){$('corpusStatus').textContent='اكتب اسماً للبحث.';return}try{if(reset||!rankedRows.length){const result=await rankedSearch(query);if(token!==request)return;rankedRows=result.results;rankedHasMore=result.has_more;rankedCompanionNote=result.companionNote}const rows=rankedRows.slice(offset,offset+25);for(const row of rows)$('corpusResults').append(action(rowLabel(row),()=>showEntry(row.id)));$('corpusStatus').textContent=rows.length?'عرض '+(offset+1)+'–'+(offset+rows.length)+' من المواضع المرشحة؛ عبارات الحكم من عنوان تقريب التهذيب فقط.':'لا توجد نتائج في المجموعة المعروضة.';$('corpusPrev').hidden=offset===0;$('corpusNext').hidden=offset+25>=rankedRows.length;if(rankedHasMore&&offset+25>=rankedRows.length)$('corpusStatus').textContent+=' توجد نتائج إضافية في قاعدة البيانات؛ ضيّق الاسم للبحث عنها.'}catch(e){if(token===request)error(e)}}
function panel(title,cls){const box=element('section',undefined,'profile-panel '+cls);box.append(element('h3',title));return box}
function table(headers){const t=element('table',undefined,'profile-table'),head=element('thead'),tr=element('tr');for(const h of headers)tr.append(element('th',h));head.append(tr);t.append(head);const body=element('tbody');t.append(body);return{table:t,body}}
function profileTabs(host,sections){const nav=element('nav',undefined,'profile-tabs');const keys=Object.keys(sections);function select(active){for(const key of keys){sections[key].hidden=key!==active;buttons[key].className='profile-tab'+(key===active?' active':'')}}const buttons={};for(const key of keys){const b=action(key,()=>select(key));buttons[key]=b;nav.append(b)}host.append(nav,...Object.values(sections));select(keys[0]);return sections}
async function showEntry(id){const token=++detailRequest,host=$('corpusDetail');host.textContent='جار فتح موضع المصدر…';let entry;try{entry=await client.entry(id)}catch(e){if(token===detailRequest)error(e);return}if(token!==detailRequest)return;
 const sourceGrade=grade({title:entry.entry.title,citation:entry.citation});const banner=element('header',undefined,'profile-hero');banner.append(element('span','مدخل مصدر · هوية تحتاج تحققاً','profile-kicker'),element('h2',entry.entry.title||'مدخل مصدر'),element('p',citation(entry.citation),'profile-citation'));host.replaceChildren(banner);
 const summary=panel('لمحة المصدر','profile-summary'),judgments=panel('الجرح والتعديل','profile-judgments'),teachers=panel('الشيوخ المذكورون','profile-teachers'),students=panel('التلاميذ المذكورون','profile-students'),source=panel('نص المصدر','profile-source');const sections={'الملخص':summary,'الجرح والتعديل':judgments,'الشيوخ':teachers,'التلاميذ':students,'نص المصدر':source};profileTabs(host,sections);
 summary.append(element('p','هذا مدخل نصي، وتطابق الاسم وحده لا يثبت اتحاد الأشخاص.','profile-caution'));judgments.append(element('p',sourceGrade?'عبارة في عنوان تقريب التهذيب: '+sourceGrade:'لا توجد عبارة حكم موجزة مستخرجة من عنوان هذا المدخل.','profile-assessment'));judgments.append(element('p','راجع النص والسياق ونسبة القول قبل تطبيقه على راوٍ في سند.','small'));
 source.append(element('p',citation(entry.citation),'rijal-source'),element('div',entry.text,'rijal-passage'),action('افتح الصفحة الأصلية كاملة',()=>showPage(entry.page_id,token,source)));
 const relationTables={teacher:table(['الاسم المذكور','مواضع المصدر','الدليل']),student:table(['الاسم المذكور','مواضع المصدر','الدليل'])};teachers.append(element('p','أسماء مستخرجة غير محسومة الهوية؛ لا تثبت السماع المباشر.','profile-caution'),relationTables.teacher.table);students.append(element('p','أسماء مستخرجة غير محسومة الهوية؛ لا تثبت السماع المباشر.','profile-caution'),relationTables.student.table);
 let identity;try{identity=await client.identity(id)}catch(e){if(token===detailRequest){summary.append(element('p','بيانات الهوية الإضافية غير متاحة في الخدمة الحالية.','small'));teachers.append(element('p','شغّل الخدمة بملف الهوية والرسم البياني لعرض العلاقات.','small'));students.append(element('p','شغّل الخدمة بملف الهوية والرسم البياني لعرض العلاقات.','small'))}return}if(token!==detailRequest)return;
 const labels={reviewed_person:'شخص روجعت هويته',needs_review:'هوية تحتاج مراجعة',provisional_cluster:'ربط مؤقت غير محسوم',unlinked_entry:'مدخل غير مربوط'};summary.append(element('p',labels[identity.identity_kind]||identity.identity_kind,'profile-status'),element('p','عدد المداخل المرتبطة: '+identity.entry_count+' · '+identity.name_key,'small'));if(identity.entry_count>1)summary.append(action('اعرض المداخل المرتبطة',()=>showMembers(identity.identity_id,token,summary)));
 try{const dates=await client.identityDates(id);if(token!==detailRequest)return;if(dates.claims?.length){summary.append(element('h3','تواريخ الوفاة المروية'));for(const claim of dates.claims){const box=element('div',undefined,'profile-date');box.append(element('span',claim.year+' هـ · '+claim.exact_quote));if(claim.page_id)box.append(action('صفحة الدليل',()=>showPage(claim.page_id,token,box)));summary.append(box)}}}catch(e){summary.append(element('p','بيانات التاريخ الإضافية غير متاحة.','small'))}
 for(const relation of ['teacher','student']){const tbody=relationTables[relation].body,group=relation==='teacher'?teachers:students;try{const graph=await client.identityGraph(id,{relation,limit:30});if(token!==detailRequest)return;for(const item of graph.results){const tr=element('tr'),name=element('td',item.name),count=element('td',String(item.source_entries)),links=element('td');if(item.mention_id)links.append(action('مواضع الدليل',()=>showEvidence(id,relation,item.mention_id,token,group)),action('هويات تذكر الاسم',()=>showMention(item.mention_id,relation,token,group)));tr.append(name,count,links);tbody.append(tr)}if(!graph.results.length)group.append(element('p','لا توجد أسماء مستخرجة في الرسم الحالي؛ هذا لا يثبت غياب العلاقة.','small'));if(graph.has_more)group.append(element('p','توجد أسماء إضافية في القاعدة.','small'))}catch(e){group.append(element('p','بيانات العلاقة الإضافية غير متاحة في الخدمة الحالية.','small'))}}
}
async function showPage(pageId,token,host){const page=await client.page(pageId);if(token!==detailRequest)return;host.append(element('p',citation(page.citation),'rijal-source'),element('div',page.text,'rijal-passage'))}
async function pageResults(host,token,fetch,render,limit=30){let offset=0;const box=element('section');host.append(box);async function more(){const result=await fetch(offset,limit);if(token!==detailRequest)return;for(const row of result.results)box.append(render(row));offset+=result.results.length;if(result.has_more){const button=action('عرض المزيد',async()=>{button.disabled=true;try{await more();button.hidden=true}catch(e){button.disabled=false;throw e}});box.append(button)}}await more()}
async function showMembers(identityId,token,host){await pageResults(host,token,(offset,limit)=>client.identityMembers(identityId,{offset,limit}),m=>action(m.name_label+' · '+m.book_id,()=>showEntry(m.entry_id)))}
async function showEvidence(entryId,relation,mentionId,token,host){const box=element('section');box.append(element('p','هذه مواضع ذكر الاسم، ولا تثبت اتحاد الهوية أو السماع.','small'));host.append(box);await pageResults(box,token,(offset,limit)=>client.graphEvidence(entryId,relation,mentionId,{offset,limit}),row=>{const item=element('div');item.append(element('p',row.entry_id+' · '+row.review_priority,'small'));if(row.page_id)item.append(action('صفحة المصدر',()=>showPage(row.page_id,token,item)));return item})}
async function showMention(mentionId,relation,token,host){const box=element('section');box.append(element('p','تشابه الاسم المذكور بين الهويات لا يثبت أن المقصود شخص واحد.','small'));host.append(box);await pageResults(box,token,(offset,limit)=>client.graphMention(mentionId,{relation,offset,limit}),row=>{const item=element('div');item.append(element('p',(row.display_name||row.identity_id)+' · '+row.source_entries+' مدخل مصدر · '+(row.identity_kind||''),'small'));item.append(action('مداخل هذه الهوية',()=>showMembers(row.identity_id,token,item)));return item})}
function chainMatch(a,b){const x=normalizedName(a).replace(/^[\s\d٠-٩.()\-–]+/u,''),y=normalizedName(b);return y.split(/\s+/).length>=2&&(x===y||x.startsWith(y+' '))}
async function chainLink(left,right){const candidates=left.results.filter(r=>headingMatch(r,left.name));if(left.name.split(/\s+/).length<2||right.name.split(/\s+/).length<2||!candidates.length||candidates.length>3)return{state:'unknown'};for(const row of candidates){try{const graph=await client.identityGraph(row.id,{relation:'teacher',limit:100});const found=graph.results.find(item=>chainMatch(item.name,right.name));if(found)return{state:'found',entry:row.id,mention:found.mention_id,source:row.citation?.title};if(graph.has_more)return{state:'unknown'}}catch(e){return{state:'unknown'}}}return{state:'missing'}}
async function showChainEvidence(link){const token=++detailRequest,host=$('corpusDetail');host.replaceChildren(element('h2','مواضع علاقة الشيخ والتلميذ'),element('p','هذه مواضع ذكر الاسم في المصدر، ولا تثبت اتحاد الهوية أو السماع المباشر.','profile-caution'));if(link.source)host.append(element('p',link.source,'rijal-source'));try{await pageResults(host,token,(offset,limit)=>client.graphEvidence(link.entry,'teacher',link.mention,{offset,limit}),row=>{const box=element('div');box.append(element('p',row.entry_id+' · '+row.review_priority,'small'));if(row.page_id)box.append(action('افتح صفحة الدليل',()=>showPage(row.page_id,token,box)));return box})}catch(e){if(token===detailRequest)host.append(element('p',e.message||String(e),'small'))}}
function showSanad(input,selected){const names=root.ShamelaSanad.parse(input);$('corpusModal').classList.remove('hidden');$('corpusResults').replaceChildren();$('corpusDetail').replaceChildren(element('h2','فحص أسماء السند في '+(selected?'النص المحدد':'الصفحة الحالية')),element('p','الأخضر: ورد الاسم في قائمة شيوخ الراوي المجاور مع دليل قابل للفتح. الأحمر: لم تُذكر العلاقة في المداخل المفحوصة فقط. الرمادي: اسم مبهم أو مرشحون متعددون أو فحص غير مكتمل. لا يحدد اللون موضع انقطاع ثابتاً ولا يحكم على صحة الحديث.','small'));$('corpusPrev').hidden=true;$('corpusNext').hidden=true;const token=++request;detailRequest++;$('corpusStatus').textContent=names.length?names.length+' أسماء مستخرجة بالترتيب · الأول: '+names[0]:'لم أتعرف على سند؛ حدد نص السند كاملا ثم أعد الفحص.';
 const bar=element('div',undefined,'sanad-chain');bar.dir='ltr';bar.setAttribute('aria-label','مسار السند من اليسار إلى اليمين');$('corpusResults').append(bar);const nodes=names.map((name,index)=>{if(index){const link=element('span','…','chain-link unknown');link.title='جار فحص العلاقة';bar.append(link)}const box=element('button',(index+1)+' · '+name,'chain-person');box.type='button';box.addEventListener('click',()=>openForName(name));bar.append(box);return box});const resultPromises=names.map((name,index)=>{const box=element('section');box.append(element('h3',(index+1)+' · '+name));$('corpusResults').append(box);return rankedSearch(name).then(result=>{if(token!==request)return null;const candidates=result.results.filter(row=>headingMatch(row,name));if(result.companionNote)box.append(element('p',result.companionNote,'small'));if(result.partial)box.append(element('p','تعذر البحث في بعض الكتب؛ أُبقيت النتائج العامة.','small'));box.append(element('p',candidates.length+' تراجم تبدأ بالاسم'+(result.has_more?'؛ قد توجد مداخل إضافية':'')+' · لا يُحسم اتحاد الأشخاص تلقائياً','small'));if(!candidates.length&&result.results.length)box.append(element('p','وجدت مواضع ذكر للاسم، لكن لا توجد ترجمة تبدأ به في النتائج الحالية. افتح جميع المواضع للمراجعة.','small'));for(const row of candidates.slice(0,10))box.append(action(rowLabel(row),()=>showEntry(row.id)));box.append(action('افتح جميع مواضع الاسم',()=>openForName(name)));return{name,results:candidates,has_more:result.has_more}},e=>{if(token===request)box.append(element('p',e.message||String(e),'small'));return null})});Promise.all(resultPromises).then(async results=>{if(token!==request)return;if(results.every(x=>!x))$('corpusStatus').textContent='تعذر البحث في قاعدة الرجال. تأكد أن الخدمة تعمل على http://127.0.0.1:8765 ثم أعد المحاولة.';const links=Array.from(bar.children).filter(x=>x.className?.includes('chain-link'));for(let i=0;i<links.length;i++){const link=links[i];let state={state:'unknown'};if(results[i]&&results[i+1]&&!results[i].has_more)state=await chainLink(results[i],results[i+1]);if(token!==request)return;link.className='chain-link '+state.state;link.textContent=state.state==='found'?'✓':state.state==='missing'?'×':'؟';link.title=state.state==='found'?'علاقة اسمية مذكورة · افتح مواضع الدليل':state.state==='missing'?'لم تُذكر العلاقة في المداخل المفحوصة':'تعذّر التحقق أو النتائج ناقصة';if(state.state==='found'){link.tabIndex=0;link.setAttribute('role','button');link.addEventListener('click',()=>showChainEvidence(state));link.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')showChainEvidence(state)})}}})}
root.showFullCorpusSanad=showSanad;root.showFullCorpus=open;root.showFullCorpusForName=openForName;root.closeFullCorpus=close;
document.addEventListener('DOMContentLoaded',()=>{$('corpusSearch').addEventListener('click',()=>search(true));$('corpusQuery').addEventListener('keydown',e=>{if(e.key==='Enter')search(true)});$('corpusPrev').addEventListener('click',()=>{offset=Math.max(0,offset-25);search(false)});$('corpusNext').addEventListener('click',()=>{offset+=25;search(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('corpusModal').classList.contains('hidden'))close()})});
})(window);
